---
lookup_options:
  '^conjur::authn_api_key':
    convert_to: 'Sensitive'
conjur::account: 'cyberark'
conjur::appliance_url: 'https://conjur.vx'
conjur::authn_login: 'host/puppet/demo'
conjur::authn_api_key: '<insert-new-api-key>'
conjur::ssl_certificate: |
  <insert-conjur-certificate>
