---
lookup_options:
  '^conjur::authn_api_key':
    convert_to: 'Sensitive'
conjur::account: 'cyberark'
conjur::appliance_url: 'https://conjur.vx'
conjur::authn_login: 'host/puppet/demo'
conjur::authn_api_key: '<insert-new-api-key>'
conjur::ssl_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIC2DCCAcCgAwIBAgIUWJGzh70q2V9krhVi6l/x4WbDmrEwDQYJKoZIhvcNAQEL
  BQAwHDEaMBgGA1UEAwwRQ2VudHJhbCBBdXRob3JpdHkwIBcNOTkxMjMxMTYwMDAw
  WhgPMjk5OTEyMzExNjAwMDBaMBQxEjAQBgNVBAMMCWNvbmp1ci52eDCCASIwDQYJ
  KoZIhvcNAQEBBQADggEPADCCAQoCggEBAOdurji7aNo6DX5SeMdC0ow+wuzYSKSO
  zt04u4smLEJKoAPwsiDeoM6rGety+Js1Hl+PQnBmyb6gRS1QupEEOBdGVxAhxXAX
  E/uRX1TVCrZTTYDd40HoU+PFu+Ugm44sremPkYOLqr2HTjaVgXtRiXcVtNUMQ2fr
  VU7WJh+y8fT9VcRE7tE1bWRYJj7yWAv8GhnpjaN/QkeYwV278Zl+wnspviH45iVT
  fkVljRnCFafoXJbOg3f+yhR0SIH1ipuoY+tzXIfc9h5WIQKhLjAOVePFPbK11hn1
  IP+6raCDlisiaotdxJ57WGXE0hvJAAmjwdQk8CsNWlxza2Vh6ghUWP8CAwEAAaMY
  MBYwFAYDVR0RBA0wC4IJY29uanVyLnZ4MA0GCSqGSIb3DQEBCwUAA4IBAQBQ1zp2
  e6/Ykt7fqB0IndOPzc6PF75qLigoCqOWq/x5KdXU9b0qtkmbWCJBHKWzLTviEGRA
  u8VXNPWs3vqD74XIthPZZOBwMFws2eYcFsgdkrgFvDSVpMK2WfXT1YZR/Dc1srRp
  1mfYyjyoQXFytEPCP6FrMAXejXYJjYz4ehHj1zVBw18mWjtvOJKfoavFRzF7ZFYL
  Cbwmm/MyFAcB+vxvi1/Toq9bxgiMhXVKsthiGc/bFcN53vR66WwXmgCtYUv56BCB
  4hXxC25BNdiwtzkJoAX/x3o5YNuZiNxWGfFpuUu81JEjx/IhUiGIuHYVxANWosq/
  kPvX/SU9q5LfQXYD
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIDGzCCAgOgAwIBAgIUedxxZ2NFxq8FCuFqNxoZPWMiZA4wDQYJKoZIhvcNAQEL
  BQAwHDEaMBgGA1UEAwwRQ2VudHJhbCBBdXRob3JpdHkwIBcNOTkxMjMxMTYwMDAw
  WhgPMjk5OTEyMzExNjAwMDBaMBwxGjAYBgNVBAMMEUNlbnRyYWwgQXV0aG9yaXR5
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvGQBMyflRLdS/9ycP2Uv
  /zuUSBOiPOKw5paEYSMHJV3kMNZWlgHHMqAnG83fYLn3JDWyI7LIPioDvIjkClhM
  GO0xr9LCxnVXrVEOf9V5TX2WD5O0AugRUfXRNrllry/FFWEovDbcjohDoEqx7rXj
  3osJ6H37V1ZdhhlYwPCblrTs/cKhoRJBwPAKhXFdDC24HnZayvU4k2I0g+ynM9TS
  N7vAAJBIZNSlAW0bOnN7PuX9ZV8ZJUDDPs5qVcTIuDDX5aWSRpfH4TkajFq+1pQw
  E+EnlOtSoC/s8vTJqdziE9vcc+zcCtB4wsgREHLK++2yH7xTIm5KBL8P8Vx/yvy1
  vwIDAQABo1MwUTAdBgNVHQ4EFgQU7FqFH6te9VaRNCYPWQ1KkIQ5k/0wHwYDVR0j
  BBgwFoAU7FqFH6te9VaRNCYPWQ1KkIQ5k/0wDwYDVR0TAQH/BAUwAwEB/zANBgkq
  hkiG9w0BAQsFAAOCAQEAnipZJ0u1TOQ6UoX5yi06v9JJ5eqRmRC0Y+EQEY4TSpxB
  pbDD2FD3xXSRAxOggTXyASOWMaghco2lLPXyUWM6UW81CJlRQlhqH+kCyWcAUgCF
  ZmDneLbcwGCjzH7nZ3px0vonx6eWaUE8h0YvMotLb95Vh/RLw4gdd48xNW7ObjVE
  jSA9mRF1l0r5dVJzyyWZJBmI+N9ZbGnYhE/5GW4Km2j0HK8CxoPvWilKZsQbIP0q
  iXk4nkWT/rdszBtRed+G9gZE9euuNE3Q7CwnvL1/+JSyKvFa0jdIv5NggKVj0skf
  Tj1Le1PVsWJzkJ4IvhP8w22XEUZG09O/n/CyGifMRw==
  -----END CERTIFICATE-----